version: "3.1"

services:
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
      - wordpress:/var/www/html
    networks:
      - internal

  database:
    container_name: ${CONTAINER_NAME}-database
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$DATABASE_ROOT_PASSWORD",
        ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - DB:/var/lib/mysql
    # command: "--default-authentication-plugin=mysql_native_password"
    networks:
      internal:
        aliases:
          - database

  wordpress:
    depends_on:
      - database
    container_name: ${CONTAINER_NAME}-wordpress
    image: wordpress:6.5.4-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: "${DATABASE_NAME}"
      WORDPRESS_DB_USER: "${DATABASE_USER}"
      WORDPRESS_DB_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - wordpress:/var/www/html
      - ./src:/var/www/html/wp-content:rw
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - database
    links:
      - database
    container_name: ${CONTAINER_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./phpmyadmin/Dockerfile
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      # ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
    ports:
      - 8081:80
    networks:
      internal:
        aliases:
          - phpmyadmin
    command:
      - "sh"
      - "-c"
      - 'echo "ServerName localhost" >> /etc/apache2/apache2.conf && apache2-foreground'

volumes:
  DB:
  wordpress:

networks:
  internal:
    driver: bridge
