# Continue with other Dockerfile instructions
FROM phpmyadmin/phpmyadmin:latest

COPY ./phpmyadmin/config/config.inc.php /etc/phpmyadmin/config.inc.php
COPY ./phpmyadmin/config/config.secret.inc.php /etc/phpmyadmin/config.secret.inc.php
